platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'web3swiftBrowser' do
  use_frameworks!
   pod 'web3swift', :path => '../../'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
