excluded:
  - Carthage
  - Pods
  - .build
  - Build
  - DerivedData

disabled_rules:
  - function_parameter_count
  - nesting
  - type_name
  - identifier_name
  - line_length
  - multiple_closures_with_trailing_closure
  - todo

opt_in_rules:
 - weak_delegate
 - unused_import
 - unneeded_parentheses_in_closure_argument
 - trailing_closure
 - static_operator
 - redundant_nil_coalescing
 - override_in_extension
 - legacy_objc_type
 - implicitly_unwrapped_optional
 - force_unwrapping
 - empty_string
 - closure_body_length
 - fallthrough
 - indentation_width

# force warnings
force_cast: error
force_try: error 

custom_rules:
  commented_out_code: 
    included: ".*\\.swift" # regex that defines paths to include during linting. optional.
    excluded: ".*Test(s)?\\.swift" # regex that defines paths to exclude during linting. optional
    name: "Commented out code" # rule name. optional.
    regex: "^\\/\\/\\s*(@|\\.?([a-z]|(\\})))" # matching pattern
    capture_group: 0 # number of regex capture group to highlight the rule violation at. optional.
    match_kinds: # SyntaxKinds to match. optional.
      - comment
    message: "No commented code in devel branch allowed." # violation message. optional.
    severity: warning # violation severity. optional.
