# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'myWeb3Wallet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myWeb3Wallet
pod 'web3swift', :git => 'https://github.com/veerChauhan/web3swift.git', :branch => 'develop'


  target 'myWeb3WalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'myWeb3WalletUITests' do
    # Pods for testing
  end

end

# set iOS deployment target for every pod to avoid warnings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
