name: Bug Report
description: File a bug report.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Please describe the bug.
      placeholder: Description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What are the steps to reproduce?
      description: Please describe the steps to reproduce the bug.
      placeholder: |
        Step 1: ...
        Step 2: ...
        Step 3: ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: Please describe the behavior you expect.
      placeholder: I expect that...
    validations:
      required: true
  - type: textarea
    id: error-thrown
    attributes:
      label: What is the error thrown?
      description: Please provide the exact error thrown.
      placeholder: Web3Error.invalidData("Exact error message")
    validations:
      required: true
  - type: textarea
    id: source-path
    attributes:
      label: What's the stack trace said?
      description: Please provide the exact source path.
      placeholder: Sources/Core/Transaction/CodableTransaction.swift:129 func recoverPublicKey()
    validations:
      required: true
  - type: textarea
    id: os-version
    attributes:
      label: OS version
      description: Please specify what platform and os version you are using?
      placeholder: macOS 13.0.1 (22A400)
    validations:
      required: true
  - type: textarea
    id: lib-version
    attributes:
      label: Library version
      description: Please specify what library version you are using?
      placeholder: 3.0.6 or "ef06fbfc735ab687ebf89c937a9d1ffe6d81d37f" commit.
    validations:
      required: true
