platform :ios, '11.2'

target 'web3swiftExample' do
  use_frameworks!
#  pod 'Alamofire', '~> 4.5'
#  pod 'BigInt', '~> 3.0.1'
#  pod 'PromiseKit', '~> 4.4'
#  pod 'AwaitKit', '~> 3.0.1'
#  pod 'PromiseKit/Alamofire', '~> 4.0'
#  pod 'CryptoSwift'
#  pod 'libsodium'
#  pod 'secp256k1_ios', '~> 0.0.6'
#  pod 'web3swift', :git => 'https://github.com/bankex/web3swift.git'
	pod 'web3swift', :path => '../../'
end
