
language: swift
osx_image: xcode11
script:
- swift build
- swift test
- xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-macOS test
- xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-iOS -destination generic/platform=iOS
- xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-watchOS
- xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-tvOS
after_success: bash <(curl -s https://codecov.io/bash)
