name: Swift

on:
  push:
    tags:
      - '*'
   
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install jazzy
      run: gem install jazzy
    - name: Generate documentation
      run: |
        jazzy \
        --clean \
        --github-file-prefix "https://github.com/attaswift/$module/tree/${GITHUB_REF}" \
        --module-version "${{ github.event.release.tag_name }}" \
        --copyright "© $(date '+%Y') [Károly Lőrentey](https://twitter.com/lorentey). (Last updated: $(date '+%Y-%m-%d'))" \
        --config .jazzy.yml
    - name: Commit docs
      run: |
        git config --local user.email "bot@github.com"
        git config --local user.name "GitHub Actions"
        git add ./docs
        git commit -m "Update docs"
        git push origin HEAD:master
